import { memo, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { getAdminReviewsAPI, updateAdminReviewVisibilityAPI } from "api/admin";
import { AdminState, ConfirmModal } from "component";
import "../admin.scss";

function ReviewsPage() {
  const { t } = useTranslation();
  const [items, setItems] = useState([]);
  const [meta, setMeta] = useState({ current_page: 1, last_page: 1, total: 0 });
  const [filters, setFilters] = useState({ q: "", rating: "", visibility: "" });
  const [pending, setPending] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const load = async (page = 1) => { setBusy(true); setError(""); try { const result = await getAdminReviewsAPI({ ...filters, page, per_page: 20 }); setItems(result.data || []); setMeta(result.meta || { current_page: 1, last_page: 1, total: 0 }); } catch (err) { setError(err?.response?.data?.message || t("admin.reviewsAdmin.loadError")); } finally { setBusy(false); } };
  useEffect(() => { load(1); }, [filters.rating, filters.visibility]);
  const change = (event) => setFilters((current) => ({ ...current, [event.target.name]: event.target.value }));
  const moderate = async () => { if (!pending) return; setBusy(true); setError(""); try { const updated = await updateAdminReviewVisibilityAPI(pending.id, !pending.is_visible); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setMessage(t("admin.reviewsAdmin.updated")); setPending(null); } catch (err) { setError(err?.response?.data?.message || t("admin.reviewsAdmin.updateError")); } finally { setBusy(false); } };
  return <main className="admin-page"><div className="container"><div className="admin-page__header"><div><h1 className="admin-page__title">{t("admin.reviewsAdmin.title")}</h1><p className="admin-page__subtitle">{t("admin.reviewsAdmin.subtitle")}</p></div></div>
    {message && <div className="admin-page__message" role="status">{message}</div>}{error && <div className="admin-page__message admin-page__message--error" role="alert">{error}</div>}
    <section className="admin-page__panel"><div className="admin-page__toolbar"><input aria-label={t("common.search")} name="q" value={filters.q} onChange={change} placeholder={t("common.search")}/><select aria-label={t("admin.reviewsAdmin.rating")} name="rating" value={filters.rating} onChange={change}><option value="">{t("admin.reviewsAdmin.allRatings")}</option>{[5,4,3,2,1].map((n) => <option key={n} value={n}>{n} ★</option>)}</select><select aria-label={t("admin.reviewsAdmin.status")} name="visibility" value={filters.visibility} onChange={change}><option value="">{t("admin.reviewsAdmin.allVisibility")}</option><option value="visible">{t("admin.reviewsAdmin.visible")}</option><option value="hidden">{t("admin.reviewsAdmin.hidden")}</option></select><button className="admin-page__button" onClick={() => load(1)}>{t("admin.common.search")}</button></div>
      <div className="admin-page__table-wrap"><table className="admin-page__table"><thead><tr><th>{t("admin.reviewsAdmin.product")}</th><th>{t("admin.reviewsAdmin.customer")}</th><th>{t("admin.reviewsAdmin.rating")}</th><th>{t("admin.reviewsAdmin.comment")}</th><th>{t("admin.reviewsAdmin.date")}</th><th>{t("admin.reviewsAdmin.status")}</th><th>{t("admin.common.actions")}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.product?.name}</td><td>{item.user?.name}<br/><small>{item.user?.email}</small></td><td>{item.rating} ★</td><td className="admin-page__long-text">{item.comment?.length > 120 ? <details><summary>{item.comment.slice(0, 120)}…</summary><p>{item.comment}</p></details> : item.comment}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td><span className={`admin-page__badge${item.is_visible ? "" : " admin-page__badge--danger"}`}>{t(item.is_visible ? "admin.reviewsAdmin.visible" : "admin.reviewsAdmin.hidden")}</span>{item.moderated_at && <small className="admin-page__moderation">{t("admin.reviewsAdmin.moderatedBy", { name: item.moderator?.name || t("admin.orders.systemActor"), date: new Date(item.moderated_at).toLocaleString() })}</small>}</td><td><button className={`admin-page__button ${item.is_visible ? "admin-page__button--danger" : "admin-page__button--ghost"}`} onClick={() => setPending(item)} disabled={busy}>{t(item.is_visible ? "admin.reviewsAdmin.hide" : "admin.reviewsAdmin.show")}</button></td></tr>)}{!items.length && !busy && <tr><td colSpan="7" className="admin-page__empty">{t("admin.reviewsAdmin.empty")}</td></tr>}{busy && !items.length && <tr><td colSpan="7"><AdminState type="loading" message={t("admin.common.loadingData")}/></td></tr>}</tbody></table></div>
      {meta.last_page > 1 && <div className="admin-page__pagination"><button disabled={meta.current_page <= 1} onClick={() => load(meta.current_page - 1)}>{t("admin.common.previous")}</button><span>{t("admin.common.pageStatus", { current: meta.current_page, last: meta.last_page, total: meta.total })}</span><button disabled={meta.current_page >= meta.last_page} onClick={() => load(meta.current_page + 1)}>{t("admin.common.next")}</button></div>}
    </section></div><ConfirmModal isOpen={Boolean(pending)} title={t("admin.reviewsAdmin.confirmTitle")} message={t("admin.reviewsAdmin.confirmMessage", { action: t(pending?.is_visible ? "admin.reviewsAdmin.hide" : "admin.reviewsAdmin.show").toLowerCase() })} onConfirm={moderate} onCancel={() => setPending(null)} busy={busy}/></main>;
}
export default memo(ReviewsPage);
